// kun käytät paikallisesti, varmista että portti on oikea, eli 3000 tai 3001
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imp1aG9rZW0iLCJpZCI6IjVmOGVjYzE5Y2EwYWY5ZTRmZjlkYWI3MCIsImlhdCI6MTYwMzQ3NDAxNH0.7uZmgC7jGrLlTph8L3FXFASJEGY22dCfXHSvyhuzkQo
// authorization käytetään, kun halutaan käyttää tokenia eli autentikoidun käyttäjän tiedon
// tokenin saa, kun kirjautuu login.js:llä

{
    "title": "Another try",
    "author": "Axl ",
    "url": "www.success.com",
    "likes": 555
}
