// kun käytät paikallisesti, varmista että portti on oikea, eli 3000 tai 3001
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Kokeillaan lisätä muistiinpano",
    "author": "John",
    "url": "www.success.com",
    "likes": 1000
}